import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Navbar } from "./components/Navbar/Navbar";
import { Hero } from "./components/Hero/Hero";
import { About } from "./components/About/About";
import { Menu } from "./components/Menu/Menu";
import { Promotion } from "./components/Promotion/Promotion";
import { Form } from "./components/Form/Form";
import { Contact } from "./components/Contact/Contact";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Ciciano</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <img
          src="https://uploads-ssl.webflow.com/6239aa5f4b436d4a462801ea/62f3bdeb87c554033b793146_cicu-hero-p-1080.jpg"
          alt=""
          className="hero_image"
        />

        <Navbar />
        <Hero />
        <About />
        <Menu />
        <Promotion />
        <Form />
        <Contact />
      </main>
    </>
  );
}
